workflows:
  android-release:
    name: Music Player Build

    environment:
      flutter: stable

    scripts:
      - git submodule update --init --recursive || true
      - flutter pub get
      - flutter build apk --release

    artifacts:
      - build/**/outputs/**/*.apk
